#pragma once
#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 1080
#define BACKGROUND_COLOR_R 96
#define BACKGROUND_COLOR_G 128
#define BACKGROUND_COLOR_B 255
#define BACKGROUND_COLOR_O 255

#define PHYS_GRAVITY_CONSTANT 9.8
#define GRAV_INCREMENT_TIMER 0.1

#define PATTERN_MOVEMENT_CONSTANT 5