#pragma once
#define SCREEN_WIDTH 1920
#define SCREEN_HEIGHT 980
#define BACKGROUND_COLOR_R 96
#define BACKGROUND_COLOR_G 100
#define BACKGROUND_COLOR_B 100
#define BACKGROUND_COLOR_O 100

#define RENDER_FPS 60
#define GAMETIME_FREQ 20

#define INPUT_SUBSYSTEM_FREQ 10
#define PHYSICS_SUBSYSTEM_FREQ 15
#define COLLISION_SUBSYSTEM_FREQ 15
#define ANIMATION_SUBSYSTEM_FREQ 20
#define EVENT_MANAGER_FREQ 1

#define PHYS_GRAVITY_CONSTANT 9.8
#define GRAV_INCREMENT_TIMER 0.1

#define PATTERN_MOVEMENT_CONSTANT 5